on: push
name: CI
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          go-version: 1.21.x
      - uses: actions/setup-go@v4
      - run: go test ./...
